/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R2026ZeroCarbonIndexRouteImport } from './routes/2026-zero-carbon/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R2026ZeroCarbonIndexRoute = R2026ZeroCarbonIndexRouteImport.update({
  id: '/2026-zero-carbon/',
  path: '/2026-zero-carbon/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2026-zero-carbon/': typeof R2026ZeroCarbonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2026-zero-carbon': typeof R2026ZeroCarbonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2026-zero-carbon/': typeof R2026ZeroCarbonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/2026-zero-carbon/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/2026-zero-carbon'
  id: '__root__' | '/' | '/2026-zero-carbon/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2026ZeroCarbonIndexRoute: typeof R2026ZeroCarbonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2026-zero-carbon/': {
      id: '/2026-zero-carbon/'
      path: '/2026-zero-carbon'
      fullPath: '/2026-zero-carbon/'
      preLoaderRoute: typeof R2026ZeroCarbonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2026ZeroCarbonIndexRoute: R2026ZeroCarbonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
